### ISSUE TITLE
Importer: File not found

### ISSUE THREAD

**Issue by KratorD** [zikula-modules/MediaModule#93]
ZK 1.4.6
MediaModule 1.2.2
Both Fresh installation.
I'm triying import files from Downloads to Mediamodule:
http://localhost:8080/test146/media/import/cmfcmfmediamodule:downloadsmodule
Result:

> Fatal error: Uncaught exception 'Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException' with message 'The file "userdata/Downloads/AxeothPortraits_HD.zip" does not exist' in C:\xampp\htdocs\test146\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser.php:123 Stack trace: #0 C:\xampp\htdocs\test146\vendor\stof\doctrine-extensions-bundle\Uploadable\MimeTypeGuesserAdapter.php(12): Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser->guess('userdata/Downlo...') #1 C:\xampp\htdocs\test146\vendor\gedmo\doctrine-extensions\lib\Gedmo\Uploadable\UploadableListener.php(246): Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter->guess('userdata/Downlo...') #2 C:\xampp\htdocs\test146\vendor\gedmo\doctrine-extensions\lib\Gedmo\Uploadable\UploadableListener.php(160): Gedmo\Uploadable\UploadableListener->processFile(Object(Gedmo\Mapping\Event\Adapter\ORM), Object(Cmfcmf\Module\MediaModule\Entity\Media\UnknownEntity), 'INSERT') #3 C:\xampp\htdocs\test146\vendor\sy in C:\xampp\htdocs\test146\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser.php on line 123

Debugging, this is the line for the fatal error:
test146/modules/cmfcmf/media-module/Importer/DownloadsModuleImporter.php
`Line 109: $this->uploadManager->markEntityToUpload($entity, ImportedFile::fromFile($file));`
The problem is "ImportedFile" because the variable "file" is OK (the file is found)
`Line 104: $file = new File($this->fileDirectory . '/' . $download['filename']);`
If the file dont exist, the error is showed in the line 104. So, I think that the problem is "ImportedFile".

Thanks.

**Comment by KratorD** [comment]
This error is only ocurring in my localhost (windows). I have tested in a server online and is working sucessfully. Thanks.
